# Use this open statement to create an OpenGL view:
/vis/open OGL 600x600-0+0  

/remoll/physlist/optical/enable

# This is the current working geometry
#/remoll/setgeofile geometry/mollerMother.gdml
/remoll/setgeofile geometry/upstream/upstreamDaughter_merged.gdml
/remoll/parallel/setfile geometry/mollerParallel.gdml 

#/remoll/likekryptonite  true

#Below the this energy, the tracks are killed
#/remoll/minEnergyCut 0 MeV

#/remoll/setphysicslist QGSP_BERT_EMV

/run/initialize


## Beam generator
/remoll/evgen/set beam
#/remoll/beamene 11.0 GeV
/remoll/beamene 123 MeV
/remoll/beamcurr 50 microampere
#/remoll/optical true
#/remoll/addfield CLEO_rm.dat
/control/execute vis/vis.mac
#/gun/position 0.0 0.0 -0.1 m
#/gun/momentum 0.5 1.0 2.0 GeV
#/remoll/beam_x0 0 mm
#/remoll/beam_y0 0 mm
/remoll/evgen/beam/origin 0 0 -100 mm

# Raster is on by default with 5x5mm
# initial angle
#/remoll/beam_th0 0 mrad
#/remoll/beam_ph0 0 mrad
# gaussian spread widths
#/remoll/beam_dth 0 mrad
#/remoll/beam_dph 0 mrad
#/remoll/evgen/beam/rasx 0 mm
#/remoll/evgen/beam/rasy 0 mm 

#/remoll/evgen/beam/isotropic true
#/remoll/evgen/beam/isotropic_theta_min 54.1 deg
#/remoll/evgen/beam/isotropic_theta_max 52.2 deg
#/remoll/evgen/beam/isotropic_theta_min 60.9319 deg
#/remoll/evgen/beam/isotropic_theta_max 60.9589 deg
#/remoll/evgen/beam/origin -987.5,0.0,-150.0 mm
#/remoll/evgen/beam/origin 0 0 -100 mm
#/remoll/evgen/beam/x -987.5 mm
#/remoll/evgen/beam/direction 0 0.0 1.0
/remoll/evgen/beam/rasx 0 mm
/remoll/evgen/beam/rasy 0 mm
#/remoll/evgen/beam/x -987.5 mm
#/remoll/evgen/beam/z -150.0 mm
#/remoll/evgen/beam/px -0.0523
#/remoll/evgen/beam/pz 0.9986 
/remoll/filename remollout_r5o_beam_default.root

## External Generator
#/remoll/evgen/set external
#/remoll/evgen/external/file remoll_moller_envelope_noCol4_noCoils_500k_LGtest_det28.root
#/remoll/evgen/external/detid 28
#/remoll/evgen/external/startEvent 0
#/remoll/evgen/external/zOffset -28550.0
#/remoll/filename remollout_r5o_external_default.root
