#  Example file

# store tracks
#/tracking/storeTrajectory 1

# This must be called before initialize
/remoll/geometry/setfile geometry/mollerMother.gdml
# Parallel world geometry is optional - detector 28 (the primary detector array's idealize vacuum detector) is included in this parallel world now.
/remoll/parallel/setfile geometry/mollerParallel.gdml 

#/remoll/physlist/register QGSP_BERT_HP
/remoll/physlist/parallel/enable 
# if optical physics is turned on it will only work if parallel physics is not turned on.
#/remoll/physlist/optical/enable 

# This must be explicitly called
/run/initialize

/remoll/printgeometry true

#/control/execute macros/load_magnetic_fieldmaps.mac

/remoll/evgen/set beam
# Raster and initial angle stuff
/remoll/oldras false
/remoll/evgen/beam/rasx 2 mm
/remoll/evgen/beam/rasy 2 mm
#/remoll/beam_x0 0 mm
#/remoll/beam_y0 0 mm
# initial angle
#/remoll/beam_th0 0 mrad
#/remoll/beam_ph0 0 mrad
# gaussian spread widths
#/remoll/beam_dth 0 mrad
#/remoll/beam_dph 0 mrad

#/remoll/evgen/set beam
# To hit Ring 5 open in septant 4
#/remoll/evgen/beam/x -1300 mm
#/remoll/evgen/beam/rasx -30 mm
#/remoll/evgen/beam/origin -0 0 -4505 mm
#/remoll/evgen/beam/direction 0 0 1 
# Mainz test energy
#/remoll/beamene 855 MeV

#/remoll/evgen/thcommin 30.0 deg
#/remoll/evgen/thcommax 150.0 deg
#/remoll/evgen/set elastic 
#/remoll/evgen/thmin 0.1 deg
#/remoll/evgen/thmax 2.0 deg
#/remoll/evgen/emin 80.0 MeV
#/remoll/evgen/set inelastic 
#/remoll/evgen/set pion
#/remoll/piontype pi+
#/remoll/evgen/set pion_LUND
#/remoll/evgen/set inelasticAl
#/remoll/evgen/set quasielasticAl
#/remoll/evgen/set elasticAl
#/remoll/evgen/set external
#/remoll/externalfile remollout.root
#/remoll/externaldetid 4051

#/remoll/evgen/beamPolarization +L
#/remoll/field/equationtype 2
#/remoll/field/steppertype 2
#/remoll/field/print

/remoll/beamene 1 GeV
/remoll/beamcurr 65 microampere

/remoll/SD/disable_all
/remoll/SD/enable 5910
/remoll/SD/detect lowenergyneutral 5901
/remoll/SD/detect secondaries 5901

/remoll/SD/enable 5902
/remoll/SD/detect lowenergyneutral 5902
/remoll/SD/detect secondaries 5902

/remoll/SD/enable 5903
/remoll/SD/detect lowenergyneutral 5903
/remoll/SD/detect secondaries 5903

/remoll/SD/enable 5904
/remoll/SD/detect lowenergyneutral 5904
/remoll/SD/detect secondaries 5904

/remoll/SD/enable 5905
/remoll/SD/detect lowenergyneutral 5905
/remoll/SD/detect secondaries 5905

/remoll/SD/enable 5906
/remoll/SD/detect lowenergyneutral 5906
/remoll/SD/detect secondaries 5906

/remoll/SD/enable 5907
/remoll/SD/detect lowenergyneutral 5907
/remoll/SD/detect secondaries 5907

/remoll/SD/enable 5908
/remoll/SD/detect lowenergyneutral 5908
/remoll/SD/detect secondaries 5908

/remoll/SD/enable 5909
/remoll/SD/detect lowenergyneutral 5909
/remoll/SD/detect secondaries 5909

/remoll/SD/enable 5910
/remoll/SD/detect lowenergyneutral 5910
/remoll/SD/detect secondaries 5910

/remoll/SD/enable 5911
/remoll/SD/detect lowenergyneutral 5911
/remoll/SD/detect secondaries 5911

/remoll/SD/enable 5912
/remoll/SD/detect lowenergyneutral 5912
/remoll/SD/detect secondaries 5912

/remoll/SD/enable 5913
/remoll/SD/detect lowenergyneutral 5913
/remoll/SD/detect secondaries 5913
/remoll/SD/detect boundaryhits 5913

/remoll/SD/enable 5914
/remoll/SD/detect lowenergyneutral 5914
/remoll/SD/detect secondaries 5914
/remoll/SD/detect boundaryhits 5914

/remoll/SD/enable 5915
/remoll/SD/detect lowenergyneutral 5915
/remoll/SD/detect secondaries 5915
/remoll/SD/detect boundaryhits 5915

# Make interactions with W, Cu, and Pb
# realistic rather than pure absorbers
#/control/execute macros/kryptonite.mac

/process/list

# Specify random number seed
/remoll/seed 123456

/remoll/filename remollout.root

#/tracking/verbose 2

#/remoll/printtargetinfo
/run/beamOn 1000
